---
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - "./src:/usr/share/nginx/html:ro"
    ports:
    - "8081:80"
