---
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: server -b http://sample1.DOMAINDOMAIN
    restart: unless-stopped
    tty: true
    working_dir: /src/minikube/site
    ports:
    - "8001:1313"
